// <auto-generated />
using Hero.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hero.API.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    [Migration("20250415122757_AddOutcomeFeedBack")]
    partial class AddOutcomeFeedBack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("OutcomeId")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConditionTypeId");

                    b.HasIndex("OutcomeId");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Effect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("OutcomeId")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EffectTypeId");

                    b.HasIndex("OutcomeId");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("Hero.Shared.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("bit");

                    b.Property<int?>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("Hero.Shared.Models.ConditionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConditionTypes");
                });

            modelBuilder.Entity("Hero.Shared.Models.EffectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EffectTypes");
                });

            modelBuilder.Entity("Hero.Shared.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StatsId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatsId")
                        .IsUnique()
                        .HasFilter("[StatsId] IS NOT NULL");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Hero.Shared.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Hero.Shared.Models.Outcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChoiceId")
                        .HasColumnType("int");

                    b.Property<string>("FeedBack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("Hero.Shared.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatsId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Hero.Shared.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Hero.Shared.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Knowledge")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Vitality")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("ItemPlayer", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.Property<int>("PlayersId")
                        .HasColumnType("int");

                    b.HasKey("ItemsId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("ItemPlayer");
                });

            modelBuilder.Entity("Condition", b =>
                {
                    b.HasOne("Hero.Shared.Models.ConditionType", "ConditionType")
                        .WithMany("Conditions")
                        .HasForeignKey("ConditionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hero.Shared.Models.Outcome", "Outcome")
                        .WithMany("Conditions")
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ConditionType");

                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("Effect", b =>
                {
                    b.HasOne("Hero.Shared.Models.EffectType", "EffectType")
                        .WithMany("Effects")
                        .HasForeignKey("EffectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hero.Shared.Models.Outcome", "Outcome")
                        .WithMany("Effects")
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EffectType");

                    b.Navigation("Outcome");
                });

            modelBuilder.Entity("Hero.Shared.Models.Choice", b =>
                {
                    b.HasOne("Hero.Shared.Models.Scene", "Scene")
                        .WithMany("Choices")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Hero.Shared.Models.Item", b =>
                {
                    b.HasOne("Hero.Shared.Models.Stats", "Stats")
                        .WithOne("Item")
                        .HasForeignKey("Hero.Shared.Models.Item", "StatsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Hero.Shared.Models.Outcome", b =>
                {
                    b.HasOne("Hero.Shared.Models.Choice", null)
                        .WithMany("Outcomes")
                        .HasForeignKey("ChoiceId");
                });

            modelBuilder.Entity("Hero.Shared.Models.Player", b =>
                {
                    b.HasOne("Hero.Shared.Models.Job", "Job")
                        .WithMany("Players")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hero.Shared.Models.Stats", "Stats")
                        .WithOne("Player")
                        .HasForeignKey("Hero.Shared.Models.Player", "StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("ItemPlayer", b =>
                {
                    b.HasOne("Hero.Shared.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hero.Shared.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hero.Shared.Models.Choice", b =>
                {
                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("Hero.Shared.Models.ConditionType", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Hero.Shared.Models.EffectType", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("Hero.Shared.Models.Job", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Hero.Shared.Models.Outcome", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Effects");
                });

            modelBuilder.Entity("Hero.Shared.Models.Scene", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Hero.Shared.Models.Stats", b =>
                {
                    b.Navigation("Item");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
