@Hero_HostAddress = http://localhost:5152

POST {{Hero_HostAddress}}/api/players/
Accept: application/json
Content-Type: application/json

{
    "name":"Warrior",
    "jobname":"warrior"
}
###

GET {{Hero_HostAddress}}/api/players/
Accept: application/json

###

GET {{Hero_HostAddress}}/api/players/1
Accept: application/json

###


DELETE {{Hero_HostAddress}}/api/players/1
Accept: application/json
